### ISSUE TITLE
Can you update it to work with Quasar?

### ISSUE THREAD

**Issue by Emasoft** [mancuniancol/script.rss2kd#1]
This is the ONLY addon that works with Shanaproject rss feed ( http://www.shanaproject.com ) and AniDB scraper.  Can you update it to work with Quasar?

**Comment by mancuniancol** [comment]
I've done the changes to support Quasar.  Could you test it for me?

**Comment by Emasoft** [comment]
Yes. Have you updated it in the quasar unofficial repo?

**Comment by mancuniancol** [comment]
No, I won't send it until I know that it is working

**Comment by Emasoft** [comment]
I've updated it manually from the zip, and configured the Quasar option. But it doesn't seem to always work. Some streams start playing with Quasar, but some others it still try to open Pulsar. Why is that?

**Comment by mancuniancol** [comment]
Only the new links will have Quasar. It means that you need to rebuild all your library

**Comment by Emasoft** [comment]
Ok, and how? Is there an option in RSS2KD for doing that? I tried the delete folder option, but you can only delete one folder at time. And I have more than 5000 of them...

**Comment by mancuniancol** [comment]
If you don't see rebuild option in the menu. It is not available then. Sorry. 
I will submit the script to the repo. Knowing that it is working. I will close this issue.
