### ISSUE TITLE
Remove releaser or fansub group from file title

### ISSUE THREAD

**Issue by Emasoft** [mancuniancol/script.rss2kd#2]
There is a problem with many RSS feeds. The kodi .strm file name and the directory name are parsed and saved including the releaser or fansub group from the file title.

This causes a mess, because the releaser or group name is written with the movie name and that makes impossible for the Kodi parsers to identify the media content.
 
Because usually the releaser or fansub group name is written in the file name between brackets (i.e. [GROUP] or (GROUP)) while the title of the episode is not, it can and should be removed from the file name when parsing the RSS feed.

Here is a Python method that does exactly this:

```python
def remove_text_inside_brackets(text, brackets="()[]"):
    count = [0] * (len(brackets) // 2) # count open/close brackets
    saved_chars = []
    for character in text:
        for i, b in enumerate(brackets):
            if character == b: # found bracket
                kind, is_close = divmod(i, 2)
                count[kind] += (-1)**is_close # `+1`: open, `-1`: close
                if count[kind] < 0: # unbalanced bracket
                    count[kind] = 0
                break
        else: # character is not a bracket
            if not any(count): # outside brackets
                saved_chars.append(character)
    return ''.join(saved_chars)

print(repr(remove_text_inside_brackets(
    "This is a sentence. (once a day) [twice a day]")))
# -> 'This is a sentence.  '
```

Can you add this filter to RSS2KD?

**Comment by mancuniancol** [comment]
This script is deprecated. It was replaced by https://github.com/mancuniancol/plugin.video.torrentrssviewer

**Comment by mancuniancol** [comment]
I use this function to get rid of brackets and another things. 

def safeName(value):  # Make the name directory and filename safe
    value = normalize(value)  # First normalization
    value = unquoteName(value)
    value = uncodeName(value)
    value = normalize(value)  # Last normalization, because some unicode char could appear from the previous steps
    value = value.lower().title().replace('_', ' ')
    # erase keyword
    value = re.sub('^\[.*?\]', '', value)  # erase [HorribleSub] for ex.
    # check for anime
    value = re.sub('- ([0-9][0-9][0-9][0-9]) ', ' \g<1>', value + " ")
    value = re.sub('- ([0-9]+) ', '- EP\g<1>', value + " ")
    if 'season' not in value.lower():
        value = value.lower().replace(" episode ", " - EP")
    # check for qualities
    value = value.replace("1920x1080", "1080p")
    value = value.replace("1280x720", "720p")
    value = value.replace("853x480", "480p")
    value = value.replace("848x480", "480p")
    value = value.replace("704x480", "480p")
    value = value.replace("640x480", "480p")
    value = value.replace("microhd", " microhd")  # sometimes comes with the year
    value = value.replace("dvdrip", " dvdrip")  # sometimes comes with the year
    keys = {'"': ' ', '*': ' ', '/': ' ', ':': ' ', '<': ' ', '>': ' ', '?': ' ', '|': ' ', '~': ' ',
            "'": '', 'Of': 'of', 'De': 'de', '.': ' ', ')': ' ', '(': ' ', '[': ' ', ']': ' ', '-': ' '}
    for key in keys.keys():
        value = value.replace(key, keys[key])
    value = ' '.join(value.split())
    return value.replace('s h i e l d', 'SHIELD').replace('c s i', 'CSI')

**Comment by Emasoft** [comment]
That script you use removes the brackets but not the CONTENT of the brackets. You should apply my filter before that.

**Comment by Emasoft** [comment]
@mancuniancol Unfortunately until you add the XEM scraper to torrentrssviewer I cannot migrate. TMDb is completely useless for scraping anime. Currently this add on is the most flexible. With rss2kd I can use the scraper I prefer. If you just fix the rss2kd parser I think that it would be perfect.

**Comment by mancuniancol** [comment]
Rss viewer has library integration too. That is the same function from script

The viewer has two function, one as addon and as script. The addon allows you to check directly. Meanwhile, the script does the integration. Same that rss2kd. 

Then, turn off the Metadata in the addon settings for speed. Then, add your rss.  In the contextual menu select the library integration and you can keep using your scraper

**Comment by Emasoft** [comment]
@mancuniancol I tried the "Manual Integration" option of torrentRSSviewer. Both from the settings and from each rss entry separatedly. But it doesn't work. It gives me ERROR. Here is the KODI debug log:

https://nopaste.me/view/972f4a96

**Comment by mancuniancol** [comment]
I will fix that then. Thank you for your feedback

**Comment by mancuniancol** [comment]
It will take me more time to fix the rss viewer because I am rewritting all the code.  I don't want to rush with that.

But, I've copied the code from the viewer to rss2kd to solve your issue.  Could you check it if it is working for you?

**Comment by Emasoft** [comment]
@mancuniancol Ok, thanks. I tried the new 1.4.1 but it gives me ERROR.
Here is the log:
https://nopaste.me/view/eb4f0f33

**Comment by mancuniancol** [comment]
This error is new.  It seems that magnet has no-latin characters.  I've added to normalize the magnet before to play it.  But, I am not sure if the magnet will be ok.  Could you check that for me, please?

**Comment by Emasoft** [comment]
Thank you, 1.4.2 works perfectly!

**Comment by mancuniancol** [comment]
Good. I will close this issue then
